# Generated by Django 3.0.6 on 2020-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todo_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_progress',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_track',
            new_name='track',
        ),
    ]
