# Generated by Django 3.0.6 on 2020-05-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('track', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
