# Generated by Django 3.0.6 on 2020-05-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='track',
            new_name='trackProgress',
        ),
    ]
